#include <as1.h>

int current_segment;
struct exec exec;
struct file current_file;
struct x_symbol* dot, * ddot;

struct x_symbol symbol_pool[SYMTAB_MAX_SIZE] = {
    { ".", 0, 0, 1, 1 },
    { "..", 0, 0, 1, 1 },

    { ".error",     P_ERROR             },
    { ".if",        P_IF,               },
    { ".else",      P_ENDIF,    0       },
    { ".endif",     P_ENDIF,    1       },
    { ".text",      P_SEGMENT,  0       },
    { ".data",      P_SEGMENT,  1       },
    { ".bss",       P_SEGMENT,  2       },
    { ".struct",    P_SEGMENT,  3       },
    { ".even",      P_EVEN,             },
    { ".mut",       P_MUT,              },
    { ".byte",      P_BYTE,             },
    { ".fill",      P_FILL,             },

    { "al",         I_REGB,     0       },
    { "cl",         I_REGB,     1       },
    { "dl",         I_REGB,     2       },
    { "bl",         I_REGB,     3       },
    { "ah",         I_REGB,     4       },
    { "ch",         I_REGB,     5       },
    { "dh",         I_REGB,     6       },
    { "bh",         I_REGB,     7       },
    { "ax",         I_REGW,     0       },
    { "cx",         I_REGW,     1       },
    { "dx",         I_REGW,     2       },
    { "bx",         I_REGW,     3       },
    { "sp",         I_REGW,     4       },
    { "bp",         I_REGW,     5       },
    { "si",         I_REGW,     6       },
    { "di",         I_REGW,     7       },
    { "bx_si",      I_REGSUM,   0       },
    { "bx_di",      I_REGSUM,   1       },
    { "bp_si",      I_REGSUM,   2       },
    { "bp_di",      I_REGSUM,   3       },
    { "es",         I_SREG,     0       },
    { "cs",         I_SREG,     1       },
    { "ss",         I_SREG,     2       },
    { "ds",         I_SREG,     3       },
    { "fs",         I_SREG,     4       },
    { "gs",         I_SREG,     5       },

    { "pusha",      O_ONEBYTE,  0x60    },
    { "popa",       O_ONEBYTE,  0x61    },
    { "nop",        O_ONEBYTE,  0x90    },
    { "cbw",        O_ONEBYTE,  0x98    },
    { "cwd",        O_ONEBYTE,  0x99    },
    { "pushf",      O_ONEBYTE,  0x9c    },
    { "popf",       O_ONEBYTE,  0x9d    },
    { "sahf",       O_ONEBYTE,  0x9e    },
    { "lahf",       O_ONEBYTE,  0x9f    },
    { "leave",      O_ONEBYTE,  0xc9    },
    { "int3",       O_ONEBYTE,  0xcc    },
    { "into",       O_ONEBYTE,  0xce    },
    { "iret",       O_ONEBYTE,  0xcf    },
    { "xlat",       O_ONEBYTE,  0xd7    },
    { "repne",      O_ONEBYTE,  0xf2    },
    { "repe",       O_ONEBYTE,  0xf3    },
    { "rep",        O_ONEBYTE,  0xf3    },
    { "hlt",        O_ONEBYTE,  0xf4    },
    { "cmc",        O_ONEBYTE,  0xf5    },
    { "clc",        O_ONEBYTE,  0xf8    },
    { "stc",        O_ONEBYTE,  0xf9    },
    { "cli",        O_ONEBYTE,  0xfa    },
    { "sti",        O_ONEBYTE,  0xfb    },
    { "cld",        O_ONEBYTE,  0xfc    },
    { "std",        O_ONEBYTE,  0xfd    },

    { "movsw",      O_STRING,   0xa5    },
    { "movsb",      X_CHSIZE            },
    { "cmpsw",      O_STRING,   0xa7    },
    { "cmpsb",      X_CHSIZE            },
    { "stosw",      O_STRING,   0xab    },
    { "stosb",      X_CHSIZE            },
    { "lodsw",      O_STRING,   0xad    },
    { "lodsb",      X_CHSIZE            },
    { "scasw",      O_STRING,   0xaf    },
    { "scasb",      X_CHSIZE            },

    { "int",        O_ARGBYTE,  0xcd    },

    { "seg",        O_SEGMENT           },
    { "sys",        O_SYS,              },

    { "add",        O_MATH0,    0       },
    { "addb",       X_CHSIZE            },
    { "or",         O_MATH0,    1       },
    { "orb",        X_CHSIZE            },
    { "adc",        O_MATH0,    2       },
    { "adcb",       X_CHSIZE            },
    { "sbb",        O_MATH0,    3       },
    { "sbbb",       X_CHSIZE            },
    { "and",        O_MATH0,    4       },
    { "andb",       X_CHSIZE            },
    { "sub",        O_MATH0,    5       },
    { "subb",       X_CHSIZE            },
    { "xor",        O_MATH0,    6       },
    { "xorb",       X_CHSIZE            },
    { "cmp",        O_MATH0,    7       },
    { "cmpb",       X_CHSIZE            },

    { "rol",        O_MATH1,    0       },
    { "rolb",       X_CHSIZE            },
    { "ror",        O_MATH1,    1       },
    { "rorb",       X_CHSIZE            },
    { "rcl",        O_MATH1,    2       },
    { "rclb",       X_CHSIZE            },
    { "rcr",        O_MATH1,    3       },
    { "rcrb",       X_CHSIZE            },
    { "sal",        O_MATH1,    4       },
    { "salb",       X_CHSIZE            },
    { "shl",        O_MATH1,    4       },
    { "shlb",       X_CHSIZE            },
    { "shr",        O_MATH1,    5       },
    { "shrb",       X_CHSIZE            },
    { "sar",        O_MATH1,    7       },
    { "sarb",       X_CHSIZE            },

    { "not",        O_MATH2,    2       },
    { "notb",       X_CHSIZE            },
    { "neg",        O_MATH2,    3       },
    { "negb",       X_CHSIZE            },
    { "mul",        O_MATH2,    4       },
    { "mulb",       X_CHSIZE            },
    { "imul",       O_MATH2,    5       },
    { "imulb",      X_CHSIZE            },
    { "div",        O_MATH2,    6       },
    { "divb",       X_CHSIZE            },
    { "idiv",       O_MATH2,    7       },
    { "idivb",      X_CHSIZE            },

    { "test",       O_TEST              },
    { "testb",      X_CHSIZE            },

    { "inc",        O_INCDEC,   0       },
    { "incb",       X_CHSIZE            },
    { "dec",        O_INCDEC,   1       },
    { "decb",       X_CHSIZE            },

    { "push",       O_STACK,    0       },
    { "pushb",      X_CHSIZE            },
    { "pop",        O_STACK,    1       },

    { NULL }
};
